version: 2.1
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.6

    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: go test ./...
      - run: go vet ./...

workflows:
  version: 2
  test:
    jobs:
      - test
